update ci

diff --git a/.github/workflows/benchmark-workflow.yml b/.github/workflows/benchmark-workflow.yml
--- a/.github/workflows/benchmark-workflow.yml
+++ b/.github/workflows/benchmark-workflow.yml
@@ -4,8 +4,8 @@ on:
   workflow_call:
 
 jobs:
-  benchmark:
-    name: benchmark
+  ldbc_benchmark:
+    name: ldbc benchmark
     env:
       NUM_THREADS: 30
       GEN: Ninja
@@ -28,7 +28,39 @@ jobs:
         with:
           name: comparison-results
           path: benchmark/compare_result.md
-      
+
+      - name: Fail if benchmark failed
+        run: |
+          if [ $(cat benchmark/exit_code) -ne 0 ]; then
+            echo "Benchmark failed"
+            exit 1
+          fi
+
+  click_benchmark:
+    name: click benchmark
+    env:
+      NUM_THREADS: 30
+      GEN: Ninja
+    runs-on: kuzu-self-hosted-benchmarking
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Build
+        run: make benchmark
+
+      - name: Benchmark
+        continue-on-error: true
+        run: |
+          set +e
+          python3 benchmark/benchmark_runner.py --dataset click --thread 10
+          echo $? > benchmark/exit_code
+
+      - name: Upload comparison results
+        uses: actions/upload-artifact@v4
+        with:
+          name: comparison-results
+          path: benchmark/compare_result.md
+
       - name: Fail if benchmark failed
         run: |
           if [ $(cat benchmark/exit_code) -ne 0 ]; then
